services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./lost-found-campus/backend
    container_name: backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build: ./lost-found-campus/backend
    container_name: frontend
    ports:
      - "3000:80"  # hostPort:containerPort
    depends_on:
      - backend  # If frontend calls backend APIs

volumes:
  mongo-data:
